export enum ActionTypes{
    SET_CURRENT_SONG = 'SET_CURRENT_SONG',
    TOGGLE_PLAYING = 'TOGGLE_PLAYING',
    SET_SONGS_ARRAY = 'SET_SONGS_ARRAY',
    PLAY = 'PLAY',
    PAUSE = 'PAUSE',
    SET_CURRENT_TIME = 'SET_CURRENT_TIME',
    SET_DURATION = 'SET_DURATION'
}